version: "3.9"
services:
  init:
    container_name: "init"
    image: alpine:latest
    restart: "no"
#    tty: true
#    build:
#      context: .
#      dockerfile: ./Dockerfile-init
    command: |
      sh -c '/run.sh'
#    entrypoint: [ "sh", "-c",  "./run.sh"]
    volumes:

      - ./init/run.sh:/run.sh:delegated
      - ./data/csv:/csv/:delegated

        #      - ./data/groups:/tangerine/groups/:delegated
#      - ./data/archives:/archives/:delegated
#      - ./data/reporting-worker-state.json:/reporting-worker-state.json:delegated
#      - ./data/client/releases:/tangerine/client/releases/:delegated
#      - ./data/client/content/groups:/tangerine/client/content/groups:delegated
#      - ./data/client/content/assets:/tangerine/client/content/assets:delegated
#      - ${PWD}/data/id_rsa:/root/.ssh/id_rsa:delegated \
#      - ${PWD}/data/id_rsa.pub:/root/.ssh/id_rsa.pub:delegated \
      - ./data/ssh:/root/.ssh:delegated \
      - ./data/state:/state:delegated \

  server:
      container_name: "server"
      image: tangerine/server
      depends_on:
        - init
        - couchdb
      build:
        context: .
        dockerfile: ./docker-build-files/Dockerfile-server
      ports:
        - "82:80"
        # - "9229:9229" # for debugging
      restart: unless-stopped
      env_file: config.env
      environment:
        - T_COUCHDB_USER_ADMIN_NAME=/run/secrets/couchdb_admin_name
        - T_COUCHDB_USER_ADMIN_PASS=/run/secrets/couchdb_admin_password
        - T_COUCHDB_ENDPOINT=http://admin:password@couchdb:5984/
        - "NODE_ENV=development"
        - NPM_DEV_MODE
      entrypoint: "/bin/sh -c \"cd /tangerine/server/ && npm run start$${NPM_DEV_MODE}\""
      volumes:
        - ./data/groups:/tangerine/groups
        - ./data/csv:/csv/:delegated
        - ./data/archives:/archives/:delegated
#        - ./data/reporting-worker-state.json:/reporting-worker-state.json:delegated
        - ./data/client/releases:/tangerine/client/releases/:delegated
        - ./data/client/content/groups:/tangerine/client/content/groups:delegated
        - ./data/client/content/assets:/tangerine/client/content/assets:delegated
        - ./content-sets:/tangerine/content-sets:delegated
        - ./server/package.json:/tangerine/server/package.json:delegated
        - ./server/src:/tangerine/server/src:delegated
        - ./client/src:/tangerine/client/src:delegated \
        - ./client/dist:/tangerine/client/dist:delegated \
        - ./server/reporting:/tangerine/server/reporting:delegated \
        - ./upgrades:/tangerine/upgrades:delegated \
        - ./scripts/generate-csv/bin.js:/tangerine/scripts/generate-csv/bin.js:delegated \
        - ./scripts/generate-csv/batch.js:/tangerine/scripts/generate-csv/batch.js:delegated \
#        - ./data/id_rsa:/root/.ssh/id_rsa:delegated \
#        - ./data/id_rsa.pub:/root/.ssh/id_rsa.pub:delegated \
        - ./translations:/tangerine/translations:delegated \
        - ./online-survey-app/src:/tangerine/online-survey-app/src:delegated \
        - ./server/entrypoint-server.sh:/tangerine/server/entrypoint-server.sh:delegated
        - ./data/ssh:/root/.ssh:delegated \
        - ./data/state:/state:delegated \

  server-ui:
    container_name: "server-ui"
    image: tangerine/server-ui
    tty: true
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./docker-build-files/Dockerfile-server-ui
    ports:
      - "81:80"
    restart: unless-stopped
    env_file: config.env
    environment:
      - T_COUCHDB_USER_ADMIN_NAME=/run/secrets/couchdb_admin_name
      - T_COUCHDB_USER_ADMIN_PASS=/run/secrets/couchdb_admin_password
      - T_COUCHDB_ENDPOINT=http://admin:password@couchdb:5984/
      - "NODE_ENV=development"
      - NPM_DEV_MODE
      - TANGY_PRE_ENTRYPOINT
#    entrypoint: "/bin/sh -c \"$${TANGY_PRE_ENTRYPOINT} cd /tangerine/server-ui/ && npm run start$${NPM_DEV_MODE}\""
#    entrypoint: "/bin/sh -c \"cd /tangerine/editor && npm run dockerdev && cd /tangerine/server-ui/ && npm run start$${NPM_DEV_MODE}\""
    entrypoint: "/bin/sh -c \"cd /tangerine/server-ui/ && npm run start$${NPM_DEV_MODE}\""
    volumes:
      - ./data/groups:/tangerine/groups
      - ./editor/package.json:/tangerine/editor/package.json:delegated
#      - ./editor/package-lock.json:/tangerine/editor/package-lock.json:delegated
      - ./editor/src:/tangerine/editor/src:delegated
      - ./server-ui/package.json:/tangerine/server-ui/package.json:delegated
      - ./server-ui/package-lock.json:/tangerine/server-ui/package-lock.json:delegated
      - ./server-ui/src:/tangerine/server-ui/src:delegated
      - ./tangy-form-editor:/tangerine/tangy-form-editor:delegated
      - ./tangy-form:/tangerine/tangy-form:delegated

  apk-generator:
    container_name: "apk-generator"
    image: tangerine/apk-generator
    tty: true
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./docker-build-files/Dockerfile-apk
    ports:
      - "83:80"
    restart: unless-stopped
    env_file: config.env
    environment:
      - T_COUCHDB_USER_ADMIN_NAME=/run/secrets/couchdb_admin_name
      - T_COUCHDB_USER_ADMIN_PASS=/run/secrets/couchdb_admin_password
      - T_COUCHDB_ENDPOINT=http://admin:password@couchdb:5984/
      - "NODE_ENV=development"
      - NPM_DEV_MODE
    entrypoint: "/bin/sh -c \"cd /tangerine/apk-generator/ && npm run start$${NPM_DEV_MODE}\""
    volumes:
      - ./data/groups:/tangerine/groups
      - ./data/csv:/csv/:delegated
      - ./data/archives:/archives/:delegated
#      - ./data/reporting-worker-state.json:/reporting-worker-state.json:delegated
      - ./data/client/releases:/tangerine/client/releases/:delegated
      - ./data/client/content/groups:/tangerine/client/content/groups:delegated
      - ./data/client/content/assets:/tangerine/client/content/assets:delegated
      - ./content-sets:/tangerine/content-sets:delegated
      - ./apk-generator/package.json:/tangerine/apk-generator/package.json:delegated
      - ./apk-generator/src:/tangerine/apk-generator/src:delegated
      - ./client/src:/tangerine/client/src:delegated \
      - ./client/dist:/tangerine/client/dist:delegated \
      - ./server/reporting:/tangerine/server/reporting:delegated \
      - ./upgrades:/tangerine/upgrades:delegated \
      - ./scripts/generate-csv/bin.js:/tangerine/scripts/generate-csv/bin.js:delegated \
      - ./scripts/generate-csv/batch.js:/tangerine/scripts/generate-csv/batch.js:delegated \
#      - ./data/id_rsa:/root/.ssh/id_rsa:delegated \
#      - ./data/id_rsa.pub:/root/.ssh/id_rsa.pub:delegated \
      - ./translations:/tangerine/translations:delegated \
      - ./online-survey-app/src:/tangerine/online-survey-app/src:delegated \
      - ./tangy-form-editor:/tangerine/tangy-form-editor:delegated
      - ./tangy-form:/tangerine/tangy-form:delegated

  nginx:
    image: 'nginx:alpine'
    container_name: nginx
    depends_on:
      - server
      - server-ui
      - apk-generator
      - couchdb
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'

  couchdb:
    container_name: "couchdb"
    depends_on:
      - init
    build:
      context: .
      dockerfile: ./docker-build-files/Dockerfile-couchdb
    ports:
      - "5984:5984"
    volumes:
      - ./data/couchdb/data:/opt/couchdb/data
      - ./data/couchdb/local.d:/opt/couchdb/etc/local.d
#    logging:
#      driver: none

secrets:
  couchdb_admin_name:
    file: ./.secrets/couchdb_admin_name.txt
  couchdb_admin_password:
    file: ./.secrets/couchdb_admin_password.txt

