version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  server:
    image: "test:latest"
    ports:
      - "80:80"
    restart: unless-stopped
    env_file: config.env
    environment:
      - T_COUCHDB_USER_ADMIN_NAME=/run/secrets/couchdb_admin_name
      - T_COUCHDB_USER_ADMIN_PASS=/run/secrets/couchdb_admin_password
      - "NODE_ENV=development"
    volumes:
      - ../tangerine/content-sets:/tangerine/content-sets:delegated
      - ../tangerine/data/dat-output:/dat-output/
      - ../tangerine/data/reporting-worker-state.json:/reporting-worker-state.json
      - ../tangerine/data/paid-worker-state.json:/paid-worker-state.json
      - ../tangerine/data/id_rsa:/root/.ssh/id_rsa:delegated
      - ../tangerine/data/id_rsa.pub:/root/.ssh/id_rsa.pub:delegated
      - ../tangerine/data/client/releases:/tangerine/client/releases/
      - ../tangerine/data/csv:/csv/
      - ../tangerine/data/archives:/archives/
      - ../tangerine/data/groups:/tangerine/groups/
      - ../tangerine/data/client/content/groups:/tangerine/client/content/groups
  editor:
    image: "editor:latest"
    ports:
      - "80:81"
    restart: unless-stopped
    env_file: config.env
    environment:
      - T_COUCHDB_USER_ADMIN_NAME=/run/secrets/couchdb_admin_name
      - T_COUCHDB_USER_ADMIN_PASS=/run/secrets/couchdb_admin_password
      - "NODE_ENV=development"
    volumes:
      - ../tangerine/content-sets:/tangerine/content-sets:delegated
      - ../tangerine/data/reporting-worker-state.json:/reporting-worker-state.json
      - ../tangerine/data/paid-worker-state.json:/paid-worker-state.json
      - ../tangerine/data/id_rsa:/root/.ssh/id_rsa:delegated
      - ../tangerine/data/id_rsa.pub:/root/.ssh/id_rsa.pub:delegated
      - ../tangerine/data/client/releases:/tangerine/client/releases/
      - ../tangerine/data/csv:/csv/
      - ../tangerine/data/archives:/archives/
      - ../tangerine/data/groups:/tangerine/groups/
      - ../tangerine/data/client/content/groups:/tangerine/client/content/groups
  couchdb:
    image: "couchdb:2"
    container_name: "couchdb"
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=/run/secrets/couchdb_admin_name
      - COUCHDB_PASSWORD=/run/secrets/couchdb_admin_password
    volumes:
      - ../tangerine/data/couchdb/data:/opt/couchdb/data
      - ../tangerine/data/couchdb/local.d:/opt/couchdb/etc/local.d

secrets:
  couchdb_admin_name:
    file: ./.secrets/couchdb_admin_name.txt
  couchdb_admin_password:
    file: ./.secrets/couchdb_admin_password.txt