version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  server:
    image: "test:latest"
    ports:
      - "80:80"
  editor:
    image: "editor:latest"
    ports:
      - "80:81"