admin:
  username: "admin"
  password: "password"
domain: "127.0.0.1"
protocol: "http://"
port: 4448
dbServerEndpoint: '/db'
appDatabase: 'app'
contentRoot: '../client-v3/content/groups'
editorClientTemplates: '../client-v3/tangy-forms/editor'
