FROM alpine:latest

RUN mkdir /tangerine
COPY ./init/id_rsa /tangerine/
COPY ./init/id_rsa.pub /tangerine/
COPY ./init/reporting-worker-state.json /tangerine/
COPY ./init/paid-worker-state.json /tangerine/
COPY ./init/run.sh /tangerine/run.sh
ENTRYPOINT ["sh"]
#CMD ["/bin/sh"]
