FROM couchdb:3

ENV COUCHDB_USER=admin
ENV COUCHDB_PASSWORD=password

COPY couchdb/local.ini /opt/couchdb/etc/

COPY couchdb/entrypoint.sh /entrypoint.sh

#RUN chmod +x /entrypoint.sh
#
#ENTRYPOINT ["/entrypoint.sh"]
