os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
services:
  - xvfb
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - npm install -g polymer-cli
install:
  - npm install 
script:
  - polymer test -l chrome 
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false

