import './tangy-form.js'
import './input/tangy-box.js'
import './input/tangy-input.js'
import './input/tangy-timed.js'
import './input/tangy-untimed-grid.js'
import './input/tangy-checkbox.js'
import './input/tangy-checkboxes.js'
import './input/tangy-checkboxes-dynamic.js'
import './input/tangy-radio-buttons.js'
import './input/tangy-select.js'
import './input/tangy-location.js'
import './input/tangy-gps.js'
import './input/tangy-acasi.js';
import './input/tangy-eftouch.js';
import './input/tangy-photo-capture.js';
import './input/tangy-video-capture.js';
import './input/tangy-qr.js';
import './input/tangy-consent.js';
import './input/tangy-partial-date.js';
import './input/tangy-toggle.js';
import './input/tangy-gate.js';
import './input/tangy-ethio-date.js';
import './input/tangy-radio-blocks.js';
import './input/tangy-prompt-box.js';
import './input/tangy-audio-playback.js';
import './input/tangy-audio-recording.js';
import './input/tangy-audio-recording-nlp.js';