admin:
  username: "admin"
  password: "password"
domain: "127.0.0.1"
protocol: "http://"
port: 80 
dbServerEndpoint: '/db'
appDatabase: 'app'
contentRoot: '../client/content'
editorClientTemplates: '../client/tangy-forms/editor'
