export class Profile {
    _id:string
    _rev:string;
    firstName:string;
    lastName:string;
    email:string;
    organizationName:string;
    organizationType:string;
    title:string;
    location:string;
    state:string;
    plan:string;
    termsOfUse;
    emailOptOut:string;
    url:string;
    username:string;
    password:string;
    collection:string;
    officialPlan:string;
    officialLastPaidAmount:string;
    officialLastPaidDate:string;
    officialContractStartDate:string;
    initialRegistration:string;
    changeTimestamp:string;
    ip:string;
    lastLoggedIn:string
}