#!/bin/bash

echo ""
echo "Tangerine Commands:"
echo ""
echo "create-group             (Create a new group with label and optional content-set)"
echo "reporting-cache-clear    (Clear all reporting caches)"
echo "reporting-worker-pause   (Pause the reporting worker to prevent reporting caches from being built)"
echo "reporting-worker-unpause (Unpause the reporting worker to continue building caches)"
echo "find-missing-records     (Find any missing records in reporting cache [experimental])"
echo "generate-csv             (Generate a CSV)"
echo "generate-uploads         (Generate fake uploads for a group)"
echo "generate-cases           (Generate cases with group's case-export.json as a template)"
echo "reset-all-devices        (Reset server tokens and device keys for all devices, requires reinstall and set up on all devices after)"
echo "push-all-groups-views     (Push all database views into all groups)"
echo "import-archives          (Import client archives from the ./data/archives folder)"
echo "release-apk              (Release a Group App as an APK)"
echo "release-pwa              (Release a Group App as a PWA)"
echo "release-dat              (Release a Group APP as a Dat Archive)"
echo "release-online-survey-app(Release an online survey app for a group/form)"
echo "translations-update      (Update translation files in all group content folders using latest)"
echo "import-v2-assessment     (Migrate an Assessment from a Tangerine v2 server to a Tangerine v3 Form)"
echo "generate-ssh-keys        (Generates new SSH keys for creating groups from remote and private content sets)"
echo "update-group-search-index(Required to run when forms.json search settings change in a group)"
echo "mysql-report             (Report on the data migration process to mysql)"
echo ""
echo "Add --help option to any command for command specific documentation."

