#!/usr/bin/env node

const DB = require(`/tangerine/server/src/db.js`)
const groupsList = require('/tangerine/server/src/groups-list.js')

if (process.argv[2] === '--help') {
    console.log('Usage:')
    console.log('       ./rename-field-value.js')
    process.exit()
}

Array.prototype.diff = function(a) {
    return this.filter(function(i) {
        return a.indexOf(i) < 0;
    });
};

function sleep(milliseconds) {
    const date = Date.now();
    let currentDate = null;
    do {
        currentDate = Date.now();
    } while (currentDate - date < milliseconds);
}


function fetchNextPage( limit, options) {
  db.allDocs(options, function (err, response) {
    if (response && response.rows.length > 0) {
      options.startkey = response.rows[response.rows.length - 1].id;
      options.skip = 1;
    }
    // handle err or response
  });
}


async function go() {
    const groupNames = await groupsList()
        // let prodDbs = {}
        // let reportingDbs = {}
        var total = 0
    for (let groupName of groupNames) {
        let reportingDbSize;
        let prodDbSize;
        let diffs;
        let duration;
        console.log(`Processing ${groupName}`)
        let docs = [];
        var limit = 1000;
        var skip = 0;
        //if (groupName == 'supervisors') { //group-d9d21b02-4f96-4def-8ed8-d8d0f8ec7103
            const prodDb = DB(`${groupName}`)
            try {
                const allDocs = await prodDb.allDocs({include_docs: false})
                let params = {limit: limit,include_docs: true, skip: 0}
                for (let i = 0; i <= Math.ceil(allDocs.rows.length/limit); i++) {
                    const theseDocs = await prodDb.allDocs(params)
                        // console.log("check out these docs: " + JSON.stringify(allDocs))
                    let x = 0
                    var isDirty = false
                    for (let doc of theseDocs.rows) {
                        // console.log(" " + JSON.stringify(doc.doc.form) + "/n")
					    if (doc.doc.form && doc.doc.form.id && doc.doc.form.title &&
		                               (doc.doc.form.id.includes('silly-sounds')
		                              ||  doc.doc.form.id.includes('somethings-the-same')
		                              ||  doc.doc.form.id.includes( 'pick-the-picture')
		                              || doc.doc.form.id.includes('arrows')
		                              || doc.doc.form.id.includes('animal-go-no-go')
									|| doc.doc.form.id.includes('sunstar') ) )  {

                            
						 for  (let item of doc.doc.items)  {   
							 //console.log(item.title)
                            var inputs = item.inputs
                            //          console.log(inputs)    
                                for (var j =0; j<inputs.length;j++) {
									if (inputs[j].name.includes('sss_cong_training_')) {
									  inputs[j].name = inputs[j].name.replace('sss_cong_training_', 'sss_cong_tr_');
									  isDirty = true;
									}
									
									if (inputs[j].name.includes('sts_training_')) {
									  inputs[j].name = inputs[j].name.replace('sts_training_', 'sts_tr_');
									  isDirty = true;
									}
									if (inputs[j].name.includes('ptp_training_')) {
									  inputs[j].name = inputs[j].name.replace('ptp_training_', 'ptp_tr_');
									  isDirty = true;
									}
									if (inputs[j].name.includes('ptp_training_') && doc.doc.form.id.includes( 'pick-the-picture' )) {
									  inputs[j].name = inputs[j].name.replace('sts_tr', 'ptp_tr');
									  isDirty = true;
									}
									if (inputs[j].name.includes('arr_training_')) {
									  inputs[j].name = inputs[j].name.replace('arr_training_', 'arr_tr_');
									  isDirty = true;
									}
									if (inputs[j].name.includes('agn_training_')) {
									  inputs[j].name = inputs[j].name.replace('agn_training_', 'agn_tr_');
									  isDirty = true;
									}
									if (inputs[j].name.includes('sun_training_')) {
									  inputs[j].name = inputs[j].name.replace('sun_training_', 'sun_tr_');
									  isDirty = true;
									}
									
									
                                }
							}
                               
                                 
                                   if (isDirty) {
                                        docs.push(doc.doc)
                                        isDirty = false
                                   }     
                                }
                                x++
                            }
                            Object.assign(params.skip += x)
                         
                    if (total <= limit) sleep(5000);
                    console.log('Limit: ' + params.limit)
                    console.log('Skip: ' + params.skip)
                    console.log('X ' + x)
                    console.log('i  ' + i)    
                    prodDb.bulkDocs(docs)
                    console.log('Push docs: ' + docs.length)
                    total += docs.length
                    console.log('TOTAL so far  ' + total)
                    docs = [];	
                }
            } catch (err) {
                console.log("error: " + err)
            }
       // } //if groupname
    }
}
go()