name: trivy-build-and-scan
on:
  push:
    branches:
      - release/v3.28.0
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/tangerine/tangerine:v3.28.0-rc-10@sha256:d9e7adfab71b5970fb507097c4a65f55524a8c5be0f607c30ee243d0614acdf2'
          format: 'sarif'
          output: 'trivy-results.sarif'
          timeout: 20m

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'